[prune]
go-tests = true
unused-packages = true

[[constraint]]
name = "github.com/gorilla/mux"
version = "1.7.0"

[[constraint]]
name = "github.com/dgrijalva/jwt-go"
version = "3.2.0"

[[constraint]]
name = "github.com/jinzhu/gorm"
version = "1.9.2"

[[constraint]]
branch = "master"
name = "golang.org/x/crypto"

[[constraint]]
name = "github.com/joho/godotenv"
version = "1.3.0"